# Generated by Django 4.2.1 on 2023-06-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('marca', models.CharField(max_length=50)),
                ('stock_disponible', models.IntegerField()),
                ('animal', models.CharField(max_length=50)),
                ('seleccionador_peso', models.BooleanField()),
                ('cantidad', models.PositiveIntegerField()),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purrfect.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=50)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purrfect.categoria')),
            ],
        ),
    ]
