# Generated by Django 4.2.2 on 2023-06-14 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purrfect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='animal',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='seleccionador_peso',
            new_name='has_peso',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='stock_disponible',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='categoria_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purrfect.animal'),
        ),
    ]
