# Generated by Django 4.2.2 on 2023-06-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfect', '0004_cargo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
