# Generated by Django 4.2.2 on 2023-06-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purrfect', '0005_user_direccion_user_subscribed_user_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purrfect.user')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purrfect.boleta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purrfect.producto')),
            ],
        ),
    ]
