# Generated by Django 4.2.2 on 2023-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purrfect', '0006_boleta_detalleboleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.CharField(default='Por enviar', max_length=20),
        ),
    ]
